/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Max;

public class App 
{
    public static int maximum(int ... list)
    {   
        int max = list[0];
        for (int i : list) {
            if(i>max) max = i;
        }
        return max;
    }
    
    public static void main(String[] args) {
        System.out.println(maximum(1,4,5,2,34,10));
    }
}
