/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e0;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
    @Test
    public void testApp() {
        assertEquals(App.solve("L"),0);
    }
}
