/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e0;

public class App {
    public static void main(String[] args) {
    }
    public static int solve(String s)
    {
        int d = 0;
            while (s.indexOf("RL")>=0)
            {
             s = s.replace("RL","LR");
             d++;   
            }
            return d;
    }
}
